### ISSUE TITLE
Enforce endianness in serial library

### ISSUE THREAD

**Issue by jeromehue** [SpaceTeam/STS1_COBC_SW#30] opened 2023-01-02 16:17 UTC
**Description**
Enforce endianness with std::endian::native, std::endian::little, std::byteswap, etc.

**Files**
Sts1CobcSw/Serial/Serial.hpp

**Comment by PatrickKa** [comment] 2023-04-12 14:31
This is a duplicate of #34.

**Closed** 2023-07-20 15:27 UTC
Labels: 1 type: feature
